unique_ids:
  assets:
    standard-page.html: YKKL6ZG44JBSMOWIXPARLHTMTWQCQT3X
    theme.css: GRRGE4VEFVGAAYRWEKS5GOCFKWADQZP4
  forms: {}
  modules: {}
  scripts: {}
  server_modules:
    ServerModule1: '1732722703076702436474530.3893'
