unique_ids:
  assets:
    standard-page.html: YKKL6ZG44JBSMOWIXPARLHTMTWQCQT3X
    theme.css: GRRGE4VEFVGAAYRWEKS5GOCFKWADQZP4
  forms:
    Form1: HCNKCF545DBRWLQSFJVVXJ2U2X67BVBT
  modules: {}
  scripts: {}
  server_modules: {}
